### ISSUE TITLE
Me tira del servidor por el uso de un "Fly" que no poseo

### ISSUE THREAD

**Issue by AlelNeon** [HeberonYT/karmaland3#1]
Hola.
Mi problemática es que al momento de acercarme a la zona seleccionada para llevar acabo la primera misión se me empezó a laguear al grado de que cuando me acerque al pequeño puente que que conecta con la casa de la primera misión me crasheo el juego, mientras en el proceso en el que intente cerrar minecraft para reinicio podia escuchar con un zombi me golpeaba, cerre el juego y volvi a entrar en el servidor, pero ahora cada vez que entro aparezco en dicho puente y automaticamente me hecha por el uso de Fly, supongo que me habre quedado buguea en el aire dado a eso lo detecta como Fly.  
![image](https://user-images.githubusercontent.com/29692823/27518634-59e86f5c-59aa-11e7-832d-a4137ddf269b.png)

**Comment by EnderHerobrina12** [comment]
me pasa lo mismo

**Comment by HeberonYT** [comment]
Hola!
Se han realizado ajustes que posiblemente sean los causantes de ese problema, por favor descarga la nueva versión del modpack he intenta ingresar nuevamente, si esto se soluciona favor de comentarlo.
http://heberon.com/
