### ISSUE TITLE
No puedo entrar al server.

### ISSUE THREAD

**Issue by DocGudrow** [HeberonYT/karmaland3#10]
Muy buenas , después de actualizar el modpack en el día de hoy me dispuse a entrar al void ya que morí allí hace un par de días y quería ir a recuperar mi tumba , desde entonces el servidor se cerro  y cada vez que intento entrar el servidor se cae . He intentado en los segundos que me carga la pantalla usar el comando para volver a mi nación pero no me da tiempo a escribir nada .  No se si es que han desactivado esta dimensión y por eso crashea o que ha sucedido , siento los inconvenientes que esta situación ha causado y por tirar a los que estaban dentro del servidor unas cuantas veces por intentar entrar.
Mil gracias de antemano por la solución . 

Un saludo !!!

**Comment by HeberonYT** [comment]
Hola, por favor menciona tu nombre de usuario en minecraft.

**Comment by DocGudrow** [comment]
Hola Heberon , mi nombre es mi nick : DocGudrow.
Mil gracias!!

**Comment by DocGudrow** [comment]
Desconocía que no se pudiera ir a esa dimensión , ahora ya estoy avisada ! Gracias nuevamente

**Comment by HeberonYT** [comment]
He reiniciado tu usuario dentro del server, eso causara que pierdas las cosas que tenias en el inventario, pero no hay otra forma de sacarte de esa dimensión.
Recuerda que NO esta permitido ir al Viod debido a problemas del mod.
Ahora ya puedes ingresar al servidor. :dancer:
