### ISSUE TITLE
Estoy baneado

### ISSUE THREAD

**Issue by Julen7620** [HeberonYT/karmaland3#11]
Soy ElHuertero, el que está baneado por estar bug en el void.
Me dijeron que contactara contigo para solucionar el problema de una forma más rápida, y bueno , aquí estoy para ayudarte y hacer que todo este proceso vaya más rápido en torno a que que banearan.
Un saludo y buenas tardes .

**Comment by DocGudrow** [comment]
Elhuertero !! yo tampoco puedo entrar XD mori ayer o antes de ayer en el void y entre hoy para recuperar mis cosas y desde entonces el server se cierra cada vez que intento entrar... :(

**Comment by Julen7620** [comment]
yo no perdí las cosas pero me pasa lo mismo que tú xD

**Comment by Julen7620** [comment]
.... bueno, espero que no las haya perdido

**Comment by HeberonYT** [comment]
Hola!
Para solucionarlo he reiniciado tu usuario dentro del server, eso causara que pierdas las cosas que tenias en el inventario.
Recuerda que NO esta permitido ir a esa dimensión del Viod debido a problemas del mod.
Ahora ya puedes intentar ingresar al servidor.
