### ISSUE TITLE
Usuario crash 

### ISSUE THREAD

**Issue by SMDG1superdoggy** [HeberonYT/karmaland3#12]
Heberon hay un mal funcionamiento o algun usuario que esta provocando un crash constante en el servidor, podrias revisarlo ?

**Comment by JonathanAbarca** [comment]
Hola, creo que mi usuario es el que bota el servidor cada vez que entro. 
Mi usuario es Paxoncito

**Comment by SMDG1superdoggy** [comment]
si, por favor no entres y espera a que Heberon resuelva la situacion

**Comment by HeberonYT** [comment]
Este problema ya esta solucionado, paxoncito ya puedes entrar a tu casa, he tenido  que borrar algunos bloques que estaban bugeados en la zona donde están tus pollos, por favor evita moverlos con pokebolas para no causar el mismo problema.
Saludos!

**Comment by JonathanAbarca** [comment]
Muchas gracias y disculpa las molestias
