### ISSUE TITLE
RANGO SE BORRA

### ISSUE THREAD

**Issue by mbedoya-dev** [HeberonYT/karmaland3#13]
Buenas tardes heberon,

Mira que pasa algo raro con el rango, a veces escribo en el chat y veo que no aparece TITAN, ni en la lista y los comandos de rango no me los permite.
Salgo y vuelvo a entrar y se arregla luego de varios intentos o a veces al solo entrar de nuevo.
![2017-07-15_18 22 38](https://user-images.githubusercontent.com/25094674/28243632-b42f560e-6997-11e7-974b-8cb3890178e4.png)
![2017-07-15_18 22 49](https://user-images.githubusercontent.com/25094674/28243634-b433d44a-6997-11e7-96af-e7b1ead74a5d.png)
![2017-07-15_18 24 03](https://user-images.githubusercontent.com/25094674/28243633-b431acce-6997-11e7-9b5c-30777966b7b6.png)

Gracias.

**Comment by HeberonYT** [comment]
Hola, esto es verdad, ya lo he comprobado antes y sucede con todos los rangos, incluso admin o Soporte. El problema esta en el plugin, el error ya fue reportado pero aún no publican actualización.
De momento te pediré que vuelvas a conectarte al server para que detecte el rango.

**Comment by mbedoya-dev** [comment]
Si, efectivamente al volver a entrar se arregla.

Gracias por la ayuda.
