### ISSUE TITLE
DUDA SOBRE MOD CHICKENS

### ISSUE THREAD

**Issue by mbedoya-dev** [HeberonYT/karmaland3#14]
Buenas Heberon,

Desde ayer no sè que pasa con mis pollos, no ponen materiales y van subiendo de tiempo, me explico.

Tengo un pollo y en nex egg me aparece los minutos, por ejemplo 500 minutos o asi, lo cual es exagerado.
![2017-07-15_19 49 18](https://user-images.githubusercontent.com/25094674/28243645-fd72cf44-6997-11e7-9474-c7e5d7e5c422.png)
![2017-07-15_19 49 22](https://user-images.githubusercontent.com/25094674/28243646-013eb886-6998-11e7-822d-52564f686521.png)

Hice lo siguiente, me traje dos pollos del nether, uno con 3 minutos para el next egg y el otro con 4 minutos.
Los recogi con las pokebols y me los traje.
Una vez en casa, note que empezaron a aumentar el tiempo, el de 3 minutos paso a 4 y el de 4 a 5 minutos.

No entiendo si es un bug mio o del server.
Ya estoy bajando de nuevo el pack, pero si puedes darme una mano, que llevo desde ayer viendo tutoriales y no encuentro la causa, jajaja.

Muchas gracias.

Mi nombre de usuario es Mauriyi.

**Comment by mbedoya-dev** [comment]
Ya descargue de nuevo y sigue la falla, cada vez suben mas los minutos de los pollos :/

**Comment by HeberonYT** [comment]
Hola!
Los pollos tienen diferente tiempo de dropeo según el nivel del pollo. Esto no es ninguna falla o error, hay que mencionar que también los tiempos se han modificado, ya que en un inicio estaban los tiempos por defecto y era muy exagerada la velocidad, por lo que muchos tenían grandes cantidades de recursos de unos cuantos pollos. Esto se ha equilibrado para no perder la esencia del juego.
