### ISSUE TITLE
No puedo entrar al server (lo tiro)

### ISSUE THREAD

**Issue by charlygamer** [HeberonYT/karmaland3#16]
![tiro](https://user-images.githubusercontent.com/30220162/28252397-a7055ce2-6a57-11e7-9267-f17953d84ef4.jpg)

Estaba dentro del server hoy 16/07/2017 y el server se estaba cayendo a cada rato (decian que alguien estaba entrando al server pero que estaba en otra dimension) yo me encontraba matando mobs en el mundo normal cuando se volvio a cerrar el server pero de ahi ya no pude entrar (a la hora de entrar me dice hots remoto desconectado) la dungeon se encuentra en el bioma de arcilla roja :)

**Comment by HeberonYT** [comment]
Buenas, parece que tu problema era debido a lo cerca que estabas de una casa bugeada del usuario paxoncito, pero esto Ya fue solucionado, así que prueba a entrar y confirma si esta resulto este problema.
Saludos!

**Comment by charlygamer** [comment]
Ya pude entrar muchisimas graciias
