### ISSUE TITLE
No puedo entrar al servidor porque tiro el servidor

### ISSUE THREAD

**Issue by ivanper** [HeberonYT/karmaland3#17]
Estaba en una dangeon en el bioma de nieve estaba matando mobs cundo porque si se cae el server y cada vez que entro se cae nombre :ivan_vallada

**Comment by HeberonYT** [comment]
Hola, por favor evita entrar al servidor hasta que se arregle tu problema, serás notificado por este medio.
Saludos!

**Comment by ivanper** [comment]
vale

2017-07-17 7:40 GMT+02:00 HeberonYT <notifications@github.com>:

**Comment by HeberonYT** [comment]
Hola! Ya fue resuelto el problema, ahora puedes ingresar nuevamente.
Saludos!

**Comment by ivanper** [comment]
gracias :)


2017-07-20 21:37 GMT+02:00 HeberonYT <notifications@github.com>:
