### ISSUE TITLE
No Puedo Entrar al Servidor Se me Crashea El juego

### ISSUE THREAD

**Issue by Xaviro** [HeberonYT/karmaland3#18]
Hola heberon te escribo para reportar un bug que tiene mi personaje que al entrar als ervidor se me cierra el juego y me crashea te pongo en adjunto la foto del error 
![error minecraft](https://user-images.githubusercontent.com/30244705/28288154-84f7cc56-6b3e-11e7-8686-0d115f18ff8c.png)

Fue un pedazo de item del Littletiles , cuando pique un pedazo de Cuarzo

https://pastebin.com/01g78SLQ

![crashxaviro](https://user-images.githubusercontent.com/30244705/28355592-f2192042-6c64-11e7-8dfa-661a6df28eb0.png)

Esta foto fue tomada en modo 1 Jugador , el item que me da problemas podria ser algo como esto

![littletiles](https://user-images.githubusercontent.com/30244705/28356192-757b7834-6c67-11e7-9524-af1a983e0b79.png)

https://cdn.discordapp.com/attachments/330611077681512450/337135397169659904/unknown.png

**Comment by HeberonYT** [comment]
Es un bloque bugeado, ya solucionado.
Saludos!
