### ISSUE TITLE
Me expulsan del servidor por uso de "FLY" que no utilizo

### ISSUE THREAD

**Issue by xXGamingDogeXx** [HeberonYT/karmaland3#2]
Cuando entre por primera vez al server hoy lunes 26/06/2017 . Acepte la primera mision y baje del arbol y me dirigi hacia el exterior, pero en una de esas, saltando puse pausa y lo cambie a pantalla completa. Hecho por el cual me crasheo y me boto del server. cuando volvi a entrar me aparecia un mensaje que decia que el uso de fly no esta permitido y solo porque el juego se cerro cuando estaba en medio de un salto. si se pudiera quisiera que me ayudes a reiniciar mi cuenta que es xX_GamingDoge_Xx (nick) para que puede hacer todo otra vez y poder entrar al servidor pronto.

**Comment by xXGamingDogeXx** [comment]
no tengo imagenes ya que en estos momentos no dispongo del celular y quisiera que me lo solucionen porfavor.

**Comment by EnderHerobrina12** [comment]
me pasa lo mismo

**Comment by xXGamingDogeXx** [comment]
Y ahora...  Que hacemos!??

**Comment by HeberonYT** [comment]
Hola!
Se han realizado ajustes que posiblemente sean los causantes de ese problema, por favor descarga la nueva versión del modpack he intenta ingresar nuevamente, si esto se soluciona favor de comentarlo.
http://heberon.com/

**Comment by xXGamingDogeXx** [comment]
Ohhhhh....  Heberon me hablo!!!!!!!!
