### ISSUE TITLE
mod chiken  tiempo muy exagerado

### ISSUE THREAD

**Issue by Zaick** [HeberonYT/karmaland3#20]
hola ya se que te pusieron otro tema parecido y bueno como dice el compañero en efecto los pollos no han soltado nada desde hace dias yo se que te gusta que le suframos y no ponernos tan facil el juego y  me parece bien incluso en skyfactory al principio te  dije que si estaba fácil pero en karmaland casi no hay mods asi que digas para enfocarte y pasarte el rato y el delos pollo era una buena opción ya que no hay un mapa de solo recursos o tienda admin donde conseguirlos y el tiempo que tenian estaba bien  porfa regresalos  como estaban normalmente que enserio ya quedaron sin utilidad  900 min dice para una pepita de oro  eso es exagerado  ya no tienen untilidad asi  o porque no pones que sea una regla solo tener a lo mucho 4 de cada uno  con su tiempo normal asi tampco exageraríamos con ellos  aunque la verdad no es tan facil  chetarte con ellos normal tardas bastante e inviertes bastante tiempo para que te salgan los pollitos y despues es estar esperando su tiempo ahi hasta que salga bueno eso es ami ver porque la verdad siento que un mod que era bueno ahora quedo obsoleto y aburrido.
De antemano te agradezco tu tiempo  y trabajo gracias

**Comment by mbedoya-dev** [comment]
Totalmente de acuerdo con el compañero. El mod quedó arruinado, ya los pollos no funcionan, yo tengo 20 pollos de diamante y desde el jueves me han soltado tres diamantes. Así optaria por tener entonces mil o mas pollos así laguee el server y se caiga, para medio obtener un stack de recursos por semana.
