### ISSUE TITLE
Error en el server al conectarme

### ISSUE THREAD

**Issue by KoopaRed** [HeberonYT/karmaland3#23]
Buenas noches.

Revisando unos temas veo que a alguien tambien le habia pasado un tema similar, al conectarme al server y cuando va a generarse el mapa, se me crashea y por consecuencia, crashea el servidor, ya me avisaron cuando intente loguearme de nuevo porque pensaba que solo era un error; me encontraba en una dungeon debajo de una torre matando enemigos y al romper un Spawn de zombis aparecieron unos 5, mas otros 5 o 6 que habian con anterioridad cerca de donde me encontraba, ya cuando escapaba aparecio un esqueleto de esos fuertes y cuando me mata, en ves de aparecer el mensajito de has muerto, aparece el mensaje de "Error por el host remoto"
![28252397-a7055ce2-6a57-11e7-9267-f17953d84ef4](https://user-images.githubusercontent.com/30520472/28706854-1174afd4-7344-11e7-933d-3c95dcfa8be7.jpg)
Ya se me dijo que no entrara de momento al server para evitar un crasheo nuevamente, no se si fue por la generacion de mobs en el lugar o por algun bloque.

**Comment by HeberonYT** [comment]
Hola!
Ya fue solucionado el problema, ahora puedes entrar al server.

Saludos!

El 28/07/2017, a las 2:24 a.m., KoopaRed <notifications@github.com<mailto:notifications@github.com>> escribió:


Buenas noches.

Revisando unos temas veo que a alguien tambien le habia pasado un tema similar, al conectarme al server y cuando va a generarse el mapa, se me crashea y por consecuencia, crashea el servidor, ya me avisaron cuando intente loguearme de nuevo porque pensaba que solo era un error; me encontraba en una dungeon debajo de una torre matando enemigos y al romper un Spawn de zombis aparecieron unos 5, mas otros 5 o 6 que habian con anterioridad cerca de donde me encontraba, ya cuando escapaba aparecio un esqueleto de esos fuertes y cuando me mata, en ves de aparecer el mensajito de has muerto, aparece el mensaje de "Error por el host remoto"
[28252397-a7055ce2-6a57-11e7-9267-f17953d84ef4]<https://user-images.githubusercontent.com/30520472/28706854-1174afd4-7344-11e7-933d-3c95dcfa8be7.jpg>
Ya se me dijo que no entrara de momento al server para evitar un crasheo nuevamente, no se si fue por la generacion de mobs en el lugar o por algun bloque.
