### ISSUE TITLE
Demasiado LAG

### ISSUE THREAD

**Issue by Im-Fran** [HeberonYT/karmaland3#24]
Hola heberon quisiera decirte que en mi notebook acer tengo 4GB de RAM y el minecraft no me corre, se queda bugueado en la pantalla principal, y eso que el karmaland 2 tenia mas mods me iba bien, mi pregunta es como puedo solucionar ese error de que se quede en la pantalla principal (le puse 4000M enves de 3GB en la ram del minecraft launcher)

Si me ayudas pronto lo agradezco

PanchoGamerYTOFICIAL

**Comment by HeberonYT** [comment]
Hola!
En equipos NoteBook no se recomienda que se ejecute el juego, debido a los bajos recursos que suelen tener esos equipos.

Por otro lado, el Modpack de karmaland 3 requiere 4gb mínimo para funcionar adecuadamente.
Si tú notebook tiene 4gb en total no puedes asignar esa misma cantidad al juego, ya que el propio sistema Windows consumirá 1gb para funcionar, eso dejaría 3gb disponibles con los cuales no te correrá el juego.
Y en cuanto a rendimiento de la tarjeta gráfica no hablamos, ya que las notebook no tienen tarjeta dedicada.

Saludos!

El 28/07/2017, a las 4:42 p.m., PanchoGamerYTOFICIAL <notifications@github.com<mailto:notifications@github.com>> escribió:


Hola heberon quisiera decirte que en mi notebook acer tengo 4GB de RAM y el minecraft no me corre, se queda bugueado en la pantalla principal, y eso que el karmaland 2 tenia mas mods me iba bien, mi pregunta es como puedo solucionar ese error de que se quede en la pantalla principal (le puse 4000M enves de 3GB en la ram del minecraft launcher)

Si me ayudas pronto lo agradezco

PanchoGamerYTOFICIAL

**Comment by PanchoGamerYTOFICIAL** [comment]
Gracias, pero eso significa que no puedo jugar katrmaland 3?
