### ISSUE TITLE
KARMALAND 3 SEMI IMPORTANTE

### ISSUE THREAD

**Issue by FlashGamer604** [HeberonYT/karmaland3#26]
En la Mision2 De karmaland 3 Mori y casi ningun admin se conecta y quisiera recuperar mis cosas mi nombre de usuario es FlashGamer604

**Comment by HeberonYT** [comment]
Hola!
Por favor mándame tus coordenadas de tu nación para yo dejarlas en tu casa cuando me conecte.

Saludos!

El 13/08/2017, a las 12:00 a.m., FlashGamer604 <notifications@github.com<mailto:notifications@github.com>> escribió:


En la Mision2 De karmaland 3 Mori y casi ningun admin se conecta y quisiera recuperar mis cosas mi nombre de usuario es FlashGamer604
