### ISSUE TITLE
MISION 2

### ISSUE THREAD

**Issue by FlashGamer604** [HeberonYT/karmaland3#28]
he Muerto en la misión 2 y tenia muchas cosas he muerto casi al inicio del tp jeje quisiera recuperar mis cosas los antes posible mi nick de usuario es FlashGamer604

**Comment by HeberonYT** [comment]
Hola!
Para entregarte las cosas debemos coincidir en entrar al server.
O mejor aún podrías darme las coordenadas de tu nación y yo te las dejaré en un cofre cuando entre.

Saludos!

El 16/08/2017, a las 8:42 p.m., FlashGamer604 <notifications@github.com<mailto:notifications@github.com>> escribió:


he Muerto en la misión 2 y tenia muchas cosas he muerto casi al inicio del tp jeje quisiera recuperar mis cosas los antes posible mi nick de usuario es FlashGamer604
