### ISSUE TITLE
me dice volar cuando no vuelo

### ISSUE THREAD

**Issue by EnderHerobrina12** [HeberonYT/karmaland3#3]
Entro al servidor y me sale en un bloque luego me hecha y si o me sale un error al llegar al suelo esto me ha pasado al salir del spawn cuando tenia lag

**Comment by HeberonYT** [comment]
Hola!
Se han realizado ajustes que posiblemente sean los causantes de ese problema, por favor descarga la nueva versión del modpack he intenta ingresar nuevamente, si esto se soluciona favor de comentarlo.
http://heberon.com/
