### ISSUE TITLE
MISION 2

### ISSUE THREAD

**Issue by FlashGamer604** [HeberonYT/karmaland3#30]
Mori en la mision 2 serca de donde te hace tp las coordenadas de mi nacion som : x: 27, z: 313, y: 56

**Comment by HeberonYT** [comment]
Hola!
Se ha devuelto el contenido de tu tumba y se colocó en tu nación en un cofre.

Saludos!

**Comment by FlashGamer604** [comment]
gracias!


2017-08-23 0:07 GMT-06:00 HeberonYT <notifications@github.com>:
