### ISSUE TITLE
me han explotado mis cosas

### ISSUE THREAD

**Issue by ThedarkproYT** [HeberonYT/karmaland3#31]
llego yo de haber explorado y veo mi casa destruida y veo un camino de bloques piedra alrededor de mi casa me rebentaron mis cofres perdi mas de 400 diamantes perdi todo exepto lo que tenia en el inventario
![2017-08-26_21 43 37](https://user-images.githubusercontent.com/31378965/29746675-b1276b1e-8aa7-11e7-9177-1bc2efc81dcb.png)
![2017-08-26_21 43 39](https://user-images.githubusercontent.com/31378965/29746676-b12d4fca-8aa7-11e7-9127-b8e5f053e927.png)

![2017-08-26_21 01 54](https://user-images.githubusercontent.com/31378965/29746664-771f5e54-8aa7-11e7-90e8-a16a7c7971b2.png)
![2017-08-26_21 01 59](https://user-images.githubusercontent.com/31378965/29746665-77217b6c-8aa7-11e7-9f93-f24edd690d61.png)

**Comment by ThedarkproYT** [comment]
Mi nación tiene todo desactivado tapie todo lo roto

**Comment by ThedarkproYT** [comment]
Tengo todo protegido😭

**Comment by HeberonYT** [comment]
Hola.
Lamento lo sucedido, pero ya he revisado tu reporte y he detectado al causante, haré lo posible por recuperar tus cosas y te avisare cuando termine.

**Comment by HeberonYT** [comment]
Al parecer no se puede recuperar tus cosas debido a que los cofres fueron reventados con TNT, supongo que tu nacion tenía activada la bandera de explosiones, de lo contrario no hubiera causado problemas el poner TNT.
Así que nadie tomó tus cosas, solo explotaron y obviamente se perdieron.
Recuerda visitar la pagina web del servidor para saber como proteger correctamente y evitar problemas futuros.

**Comment by ThedarkproYT** [comment]
Yo tenia lo de explosiones para que no pasara 😭
