### ISSUE TITLE
Me echa del servidor y tengo TITAN

### ISSUE THREAD

**Issue by DJsoynico** [HeberonYT/karmaland3#34]
El tema es el siguiente, una persona entro a mi cuenta y me cambio el nombre y ahora por 30 dias tengo ese nombre, y el servidor me echa cuando entro, nose si sera por esto o por que, mi nombre en el server siempre fue DJsoynico , eh pasado muchas horas y ayudado a muchos dentro del juego 
No se por que no me dejara entrar , pero si se puede solucionar estaria agradecido.

Desde ya muchas gracias!

**Comment by HeberonYT** [comment]
Hola!
Por favor revisa que tengas la última versión del Modpack, ya que recientemente se actualizo.
Para descargar la última versión visita www.heberon.com Pestaña "Servidores".
Si esto no soluciona el problema, necesitaré que coloques más información sobre el error, una captura de pantalla, etc.

**Comment by HeberonYT** [comment]
estoy revisando tu caso, es difícil identificar el problema, te avisaré cuando lo tenga solucionado.

**Comment by HeberonYT** [comment]
Solucionado!
