### ISSUE TITLE
Explosion

### ISSUE THREAD

**Issue by ThedarkproYT** [HeberonYT/karmaland3#35]
Me podria por oo menos devolver algo de los cofres? Pls

**Comment by ThedarkproYT** [comment]
Soy el usuario que le reventaron la casa ThedarkproYT

**Comment by HeberonYT** [comment]
No puedo devolver cosas que has perdido por descuido, no lo tomes a mal, pero es responsabilidad de cada usuario el tener configurada y protegida su nación.
Obviamente otro usuario causó las explosiones, y créeme que tendrá castigo, pero también es decisión tuya el activar o desactivar las banderas de tu nación, como las explosiones, por ello todo esto lo expliqué en el tutorial de protección.

**Comment by ThedarkproYT** [comment]
Heberon te dire una cosa yo e estado en casa de otros jugadores con lo de explosiones desactivado y ahn explotado creepers y han destruido parte y como responsable dejo un cartel y los bloques de la parte destruida y yo tenia eso de la abndera de explosiones desactivado eso es un bug

**Comment by ThedarkproYT** [comment]
Pero si dices que no puedes dar nada lo admitire me apañare 😭
