### ISSUE TITLE
de nuevo mi casa destruida

### ISSUE THREAD

**Issue by ThedarkproYT** [HeberonYT/karmaland3#36]
entro al server y veo mi casa de neuvo destruida heberon has algo pls
![2017-08-28_17 27 29](https://user-images.githubusercontent.com/31378965/29796367-4fbeddf6-8c16-11e7-95e6-b41bfe2e45dc.png)
![2017-08-28_17 27 34](https://user-images.githubusercontent.com/31378965/29796368-4fbee418-8c16-11e7-8564-eeca6a4f7508.png)
![2017-08-28_17 27 39](https://user-images.githubusercontent.com/31378965/29796366-4fbcfc70-8c16-11e7-8eca-42a9b837459a.png)
![2017-08-28_17 27 44](https://user-images.githubusercontent.com/31378965/29796369-4fc2652a-8c16-11e7-9876-e6c91e6cdaea.png)
![2017-08-28_17 27 59](https://user-images.githubusercontent.com/31378965/29796370-4fc7ab2a-8c16-11e7-86a5-3715bee1d61c.png)

**Comment by ThedarkproYT** [comment]
espero tu respuesta heberon que hago... entre al server por dievrsion

**Comment by ThedarkproYT** [comment]
Resulta que si ponen una dinamita a 1 bloque de mi nacion por un bug explota parte de mi nacion asi heberon ya no es culpa mia ya hoy perdi mas cosas perdi cosas valiosisimas del voidcraft y eso no se recupera facil perdi como 16 cubos llenos de liquido void que hago 😭😭😭

**Comment by HeberonYT** [comment]
Hola de nuevo.
He revisado este asunto y tienes razón, hay un bug que permite que las explosiones externas causen daños en el borde de tu nación.
Mañana revisaré quien fue el usuario para darle Ban.

**Comment by ThedarkproYT** [comment]
Gracias me tendre que mudar ya perdi todo practicamente

**Comment by HeberonYT** [comment]
Te informo que las pruebas señalan a Broly888 TITAN como causante de las explosiones, lo hizo colocando TNT en las paredes de tu nación, también fue el quien colocó los bloques para escalar, utilizo piedra del chisel y bloques de iron ore.
Fue baneado por 10 días como advertencia, si vuelve a causar mas problemas será baneado permanente.
Lamento los problemas que se causaron en tu nación, por favor menciona en la parte de abajo una lista de objetos que perdiste para reponer parte de ellos.
Saludos!

![screenshot_1](https://user-images.githubusercontent.com/13698597/29895131-9b3479ca-8d9d-11e7-933b-d32e860ca6c7.png)

**Comment by ThedarkproYT** [comment]
Hola lamento la demora pero por cuestiones del colegio no pude responderte hasta ahora creo que ya no necesito nada ya consegui todo gracias a los jugadores nadamas quiero mis 64 de oro en mena pls y 4 cubos de liquido void

**Comment by ThedarkproYT** [comment]
pero si me lo cambia por un rango se lo agradeceria

**Comment by HeberonYT** [comment]
Por ser el primero en reportar el bug de las explosiones te otorgaré el rango, la activación se hará en los siguientes días.
Saludos!
