### ISSUE TITLE
SOY TITAN Y NO ME HAN DADO NADA

### ISSUE THREAD

**Issue by MJRAW** [HeberonYT/karmaland3#38]
hola he comprado el rango titan y no me han dado las armaduras y demas cosas....

**Comment by HeberonYT** [comment]
Hola!
Primero que nada, gracias por tu apoyo al servidor, cada rango ayuda a mantener abierto este y otros servidores.

Sobre las cosas incluidas en el rango, te comento que no se entregan automáticamente.
Tu debes ingresar el comando "**/kit titan**" para que se entregue todo lo que se describe en la pagina web.

Recuerda que en el mercado de los NPC, el herrero te encantará tu armadura, espada y alas, también puede llevarla con el para que te la repare cuantas veces sea necesario.
_Saludos!_
