### ISSUE TITLE
TNT en home´s 

### ISSUE THREAD

**Issue by Bernal096** [HeberonYT/karmaland3#39]
![21267550_1974610836152853_1887462397_o](https://user-images.githubusercontent.com/31494514/29901971-d1d85870-8dc0-11e7-9d33-f595cff13183.jpg)
![Uploading 21277855_1974610789486191_1489963599_o.jpg…]()

Heberon anteriormente ThedarckproYT reporto creo a ti un problema con que estan poniendo TNT a un lado de los limites de los home osea donde ya  es territorio libre a un bloque tuyo la explotan y alcanz por un bug a romper un pedazo de tu cas o muralla o lo que tengas a continuacion te anexo fotos de varios home que tengo a lado de mi casa incluyendome que fueron explotados. Porfavor exigimos un banneo a este tipo de personas, por la acciones que estan cometiendo. 
![21245814_1974610889486181_662954924_o](https://user-images.githubusercontent.com/31494514/29901873-32702a38-8dc0-11e7-90b3-cdf749919a6b.jpg)
![21245946_1974610812819522_1619618813_o](https://user-images.githubusercontent.com/31494514/29901874-327409be-8dc0-11e7-80e1-53460c3cea49.jpg)
![21247926_1974610842819519_352162906_o](https://user-images.githubusercontent.com/31494514/29901875-32791dc8-8dc0-11e7-95c1-0a44c124b573.jpg)

**Comment by HeberonYT** [comment]
Hola!
Efectivamente ya me reportaron los daños de una nación.
Hace un rato di respuesta a ese usuario y fue baneado el causante.
Si hay otra nación afectada, necesito que el dueño sea quien lo reporte para que proporcione más información.

Saludos!
