### ISSUE TITLE
fui al end y apareci muerto 

### ISSUE THREAD

**Issue by Julen7620** [HeberonYT/karmaland3#5]
hola Heberon, esta mañana me dispuse a ir al end al ver que ya lo habían abierto,( fui con mi compañera de casa ella te lo puede verificar) pues al grano.. entre aparecí cayendo y acto seguido mori al caer por el precipicio(sin tocar la "isla". Hable con Cauchalero y me dijo que no encontraba mi tumba por ningún rincón del end aun así con la hoja de muerte.
Espero que me respondas y que se pueda solucionar por que tarde días y un montones para conseguir las cosas que tenia encima.
Nick: ElHuertero. 
Gracias y un saludo

**Comment by HeberonYT** [comment]
Las personas que mueren por caída en el END, su tumba aparece en el VIOD, es necesario ir a esa dimensión y seguir las coordenadas para su ubicación.
