### ISSUE TITLE
Rango fanatico (no da las cosas con ligado alma)

### ISSUE THREAD

**Issue by castyy** [HeberonYT/karmaland3#6]
Buenas, compre el rango fanatico y las cosas del kit han venido con proteccion 1 en vez de ligado alma. No muero por el tema pero capaz pueda suceder con otros rangos tambien. Y si quiera subir mi rango de aca a  1 semana a titan, tengo que pagar 10 dolares mas o los 20 completos? si son los 10 como lo haría?
Saludos y muchas gracias.
![2017-07-06_03 32 17](https://user-images.githubusercontent.com/29940978/27898316-d530d6e6-61fb-11e7-8aef-e2a4c386c7b3.png)
![2017-07-06_03 32 23](https://user-images.githubusercontent.com/29940978/27898314-d52eed90-61fb-11e7-93b3-84087a716e2c.png)
![2017-07-06_03 32 24](https://user-images.githubusercontent.com/29940978/27898315-d52ef6fa-61fb-11e7-9425-6e806e3276a6.png)

**Comment by HeberonYT** [comment]
Hola!
El tema del encantamiento lo estoy solucionando cambiando personalmente las armaduras por unas que tengan ligado al alma.
Sobre el rango, se colocarán en buycraft las actualizaciones de rangos, solo pagaras una diferencia de precio.
