### ISSUE TITLE
Usuario incontrolable

### ISSUE THREAD

**Issue by SMDG1superdoggy** [HeberonYT/karmaland3#7]
Hola Heberon podrias mandar a alguien a moderar a unos usuarios..
![captura de pantalla 363](https://user-images.githubusercontent.com/29807096/27936249-6fe6eb48-6275-11e7-96d4-c603f9f0f117.png)

![captura de pantalla 364](https://user-images.githubusercontent.com/29807096/27936202-3bc19c78-6275-11e7-9507-5e5eba2c7d4d.png)
![captura de pantalla 365](https://user-images.githubusercontent.com/29807096/27936208-40775b72-6275-11e7-931a-46a87ecef4f8.png)

**Comment by HeberonYT** [comment]
ya fue baneado, gracias por la info.
