### ISSUE TITLE
problema con java o nose que mi pc es 32 bits procesador x64 y 4gb ram ojala que me puedas ayudar asi podre jugar tu maravilloso server! ojala que me resuelvas el problema

### ISSUE THREAD

**Issue by facuudev** [HeberonYT/karmaland3#8]
![captura](https://user-images.githubusercontent.com/29964088/27937275-380de46c-628c-11e7-9456-96b3b8482654.PNG)

**Comment by elbanilejo77** [comment]
muy buenas Facundo0555 trata cambiando el java a una version mas vieja, el modpack por defecto se asigna 3gb de ram, asi que te correra pero en ocasiones te ira un poco lento

**Comment by facuudev** [comment]
Como cual version maso menos??

**Comment by elbanilejo77** [comment]
java 7 y de hay ya que arranques el pack que el solo se actualize

**Comment by facuudev** [comment]
Osea lo dejo cargando al mods pack con java 7 y con cuantas 3gb??

**Comment by HeberonYT** [comment]
con 3gb de ram te correrá, un poco mal pero correrá. lo recomendable es asignar de 4gb en adelante.

**Comment by facuudev** [comment]
Ok gracias heberon sos el mejor el mejor
