### ISSUE TITLE
Problema al cargar mod.

### ISSUE THREAD

**Issue by MrSuperNuts** [HeberonYT/karmaland3#9]
Saludos, la verdad me incomoda tener que molestar en el foro debido a esto pero e intentado de todo para que funcione, al parecer logré ejecutar bien todo pero no puedo hacer que pase de ahí, se queda en eso del bounding boxes - barrel y no pasa ni por error.

![image](https://user-images.githubusercontent.com/29993726/27982368-9e188f12-6365-11e7-9b79-8d51476099bb.png)

**Comment by HeberonYT** [comment]
Esto se soluciona asignando mas memoria RAM al perfil del juego.
